### PR TITLE
Function to create scale bar

### LINKED ISSUE #144: Scale bar option
Add optional param to SRCGrob to use scale bars instead of y-axes. 

Screenshot 2024-09-20 at 2 39 33 PM

Using a scale bar allows users to estimate the distance for each edge, even when the edges are not vertical. It may not provide perfect precision, but it avoids the misleading visual representation caused by a y-axis, which can distort the perceived distances between nodes. Additionally, when using 2 edges, this allows us to indicate which edge corresponds to which value (blue vs. dashed black line below) without using figure captions.

### PR DESCRIPTION
**Pull request by whelena**
# Description
Add scalebar option to tree plots

### Closes #144 

# Checklist

- [x] This PR **does *NOT* contain** Protected Health Information [(PHI)](https://ohrpp.research.ucla.edu/hipaa/). A repo may ***need to be deleted*** if such data is uploaded. <br> Disclosing PHI is a ***major problem***[^1] - Even ***a small leak can be costly***[^2].
  
- [x] This PR **does *NOT* contain** germline genetic data[^3], RNA-Seq, DNA methylation, microbiome or other molecular data[^4].

[^1]: [UCLA Health reaches $7.5m settlement over 2015 breach of 4.5m patient records](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m)
[^2]: [The average healthcare data breach costs $2.2 million, despite the majority of breaches releasing fewer than 500 records.](https://www.ponemon.org/local/upload/file/Sixth%20Annual%20Patient%20Privacy%20%26%20Data%20Security%20Report%20FINAL%206.pdf)
[^3]: [Genetic information is considered PHI.](https://www.genome.gov/about-genomics/policy-issues/Privacy#:~:text=In%202013%2C%20as%20required%20by,genetic%20information%20for%20underwriting%20purposes.)
  [Forensic assays can identify patients with as few as 21 SNPs](https://www.sciencedirect.com/science/article/pii/S1525157817305962)
[^4]: [RNA-Seq](https://www.nature.com/articles/ng.2248), [DNA methylation](https://ieeexplore.ieee.org/document/7958619), [microbiome](https://www.pnas.org/doi/pdf/10.1073/pnas.1423854112), or other molecular data can be used to predict genotypes (PHI) and reveal a patient's identity.

- [ ] This PR **does *NOT* contain** other non-plain text files, such as: compressed files, images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other output files.

_&emsp; To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for example._

- [x] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [x] I have set up or verified the `main` branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [ ] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using [AD_username (or 5 letters of AD if AD is too long)]-[brief_description_of_branch].
  
- [x] I have added the major changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

### CODE REVIEW

**Comment by whelena** [comment]
Creating a draft PR so I can note the changes I made to your version in case it causes confusion.

1. Integrate `create.scale.bar` function into `SRCGrob` by adding 2 params: `scale.bar = <logical>` and `scale.bar.coords = c(left.x, top.y)`
2. Add function to call `create.scale.bar` for each y axis defined by the user
3. Add helper function to pick a scale bar size (`get.scale.bar.length`) and to take the most common values in the tree column to determine the scale bar colour, line type and line width
4. Removed `visual.length` param from the `create.scale.bar` function so everything is defined relative to the `scale.length`

**Comment by whelena** [comment]
The force push is to remove a merge commit that commited unrelated files

**Comment by whelena** [comment]
I'd recommend running a few fuzz tests to evaluate the robustness of the scalebars with varying axis values. I tested with two edges using different scales, but it would be helpful to test on scales that differ by a few orders of magnitude.
multi-sample_dend-two-edge

**Review by dan-knight — APPROVED** [review]
Looks good! The separate viewport approach is ideal in my opinion. We may even want to refactor some other code to use this in future. Anyway, looks great. Most common value is a good default. We can even add the option to specify the scalebar style in future.

Have we thought about what might happen if someone wants one y-axis and one scalebar? Am I right that this code would support that as written?

**Comment by whelena** [comment]
> Have we thought about what might happen if someone wants one y-axis and one scalebar? Am I right that this code would support that as written?

It wont support that because the current `add.axes` and `add.scale.bar` function takes both scales/lengths in `make.clone.tree.grobs`. To implement your suggestion we need to generalise the processing of each length, but for now they're always processed together I believe.

**Pull request merged**
